name: molecule-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          path: "${{ github.repository }}"
          molecule_command: "test"
      - uses: gofrolist/molecule-action@v2
